###############################################################################
# DeltaRedisBungee Configuration File
###############################################################################

# Login and connection information for the Redis server
redis:
  host: localhost
  port: 6379
  password: null

# Name        | Type
# ------------------------
# MrRoboto    | BungeeCord
# Diamond     | Spigot
# Gold        | Spigot
# Iron        | Spigot

# Name of this BungeeCord instance
# From the example, this should be set to 'MrRoboto'.
proxy-name: bungee

# Formatting Strings
formats:

  NoPerm: "&4&lFAILURE &8> &7You do not have the {0} permission."
  Usage: "&b&lUSAGE &8> &7{0}"
  PlayerOffline: "&4&lFAILURE &8> &7Player {0} is offline"
  PlayerOnlyCommand: "&4&lFAILURE &8> &7Only in-game players can use {0}"

  CommandSent: "&a&lSUCCESS &8> &7Command sent to {0}"
  ServerNotFound: "&4&lFAILURE &8> &7Server {0} is not online or does not exist"
  DebugCategoryChange: "&a&lSUCCESS &8> &7Debug category {0} has been set to {1}"


# Used for debugging DeltaRedisBungee
debug: False
